typography_spectrum: 0.3136201
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.8315412
title: Kids Games Rock
purpose: []
color:
  saturation: 0.7325214
  brandStrength: 0.6630824
  rhythmicContrast: 0.7777778
  brandColors:
    - '#140F0F'
    - '#EAD6DA'
    - '#AB9B77'
    - '#273277'
    - '#EA2716'
  lightness: 0.8548387
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: "Kids' Games Rock"
