name: "Kids' Games Rock"
favicon: null
layout_spectrum: 0.31456811004318297
typography_spectrum: 0.9694381111767143
title: Kids Games Rock
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7faff'
    - '#53575a'
    - '#b4a9ad'
    - '#d6d2d3'
    - '#9f836e'
  brandStrength: 0.603520589414984
  lightness: 0.3113226427230984
  saturation: 0.7325213765725493
  rhythmicContrast: 0.30467105749994516
purpose: []
